version: '3'

services:
  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27107:27017

  
  mongo-express:
    image: mongo-express
    ports:
      - 27108:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  eventstore:
    image: eventstore/eventstore
    ports:
      - 1113:1113
      - 2113:2113
    environment:
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
